// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJCQi2Nl9UXhZlYMAof4vCIXK-H_o8v8Q',
    appId: '1:1095517098932:web:23d7f81e90e60301ee98e1',
    messagingSenderId: '1095517098932',
    projectId: 'hello-world-fb922',
    authDomain: 'hello-world-fb922.firebaseapp.com',
    storageBucket: 'hello-world-fb922.appspot.com',
    measurementId: 'G-SJEYHRNKTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcWpP5QDJ5Eg-M9ZHZ11LYdRRCm3_WKHU',
    appId: '1:1095517098932:android:3b18749c48052716ee98e1',
    messagingSenderId: '1095517098932',
    projectId: 'hello-world-fb922',
    storageBucket: 'hello-world-fb922.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz-uiBosk3fkq8oDJtLVE5YuhVfxSFBqk',
    appId: '1:1095517098932:ios:c72bb3e0aa7b3a73ee98e1',
    messagingSenderId: '1095517098932',
    projectId: 'hello-world-fb922',
    storageBucket: 'hello-world-fb922.appspot.com',
    iosClientId: '1095517098932-p14h43u7hg3acp8esv1734re0tdqt4gs.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
